spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/stress?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        #        generate_statistics: true
        show_sql: true
        format_sql: true
        #        batch_versioned_data: true
        #        order_inserts: true
        #        order_updates: true
        #        use-new-id-generator-mappings: false
        #        jdbc:
        #          batch_size: 200
        use_sql_comments: true
  flyway:
    enabled: false
    baseline-on-migrate: true
    url: jdbc:mysql://localhost:3306/stress?serverTimezone=UTC&characterEncoding=UTF-8&rewriteBatchedStatements=true&rewriteBatchedStatements=true
    user: root
    password: root
logging.level:
  org.hibernate.SQL: debug